CREATE OR ALTER TABLE WS_DEMO_DB.STG.ORDERS_STG (
    ORDER_ID NUMBER,
    CUSTOMER_ID NUMBER,
    ORDER_STATUS VARCHAR,
    TOTAL_PRICE NUMBER,
    ORDER_DATE DATE,
    ORDER_PRIORITY VARCHAR,
    CLERK VARCHAR,
    SHIP_PRIORITY NUMBER,
    LOAD_TIMESTAMP TIMESTAMP
);

MERGE INTO WS_DEMO_DB.STG.ORDERS_STG AS TGT
USING WS_DEMO_DB.EX.ORDERS_EX AS SRC
ON TGT.ORDER_ID = SRC.O_ORDERKEY
WHEN MATCHED THEN
    UPDATE SET 
        CUSTOMER_ID = SRC.O_CUSTKEY,
        ORDER_STATUS = SRC.O_ORDERSTATUS,
        TOTAL_PRICE = SRC.O_TOTALPRICE,
        ORDER_DATE = SRC.O_ORDERDATE,
        ORDER_PRIORITY = SRC.O_ORDERPRIORITY,
        CLERK = SRC.O_CLERK,
        SHIP_PRIORITY = SRC.O_SHIPPRIORITY,
        LOAD_TIMESTAMP = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN
    INSERT (
        ORDER_ID,
        CUSTOMER_ID,
        ORDER_STATUS,
        TOTAL_PRICE,
        ORDER_DATE,
        ORDER_PRIORITY,
        CLERK,
        SHIP_PRIORITY,
        LOAD_TIMESTAMP
    )
    VALUES (
        SRC.O_ORDERKEY,
        SRC.O_CUSTKEY,
        SRC.O_ORDERSTATUS,
        SRC.O_TOTALPRICE,
        SRC.O_ORDERDATE,
        SRC.O_ORDERPRIORITY,
        SRC.O_CLERK,
        SRC.O_SHIPPRIORITY,
        CURRENT_TIMESTAMP()
    );