CREATE OR ALTER TABLE WS_DEMO_DB.STG.PART_STG (
    PART_ID NUMBER,
    PART_NAME VARCHAR,
    PART_MANUFACTURER VARCHAR,
    PART_BRAND VARCHAR,
    PART_TYPE VARCHAR,
    PART_SIZE NUMBER,
    CONTAINER VARCHAR,
    RETAIL_PRICE NUMBER,
    LOAD_TIMESTAMP TIMESTAMP
);

MERGE INTO WS_DEMO_DB.STG.PART_STG AS TGT
USING WS_DEMO_DB.EX.PART_EX AS SRC
ON TGT.PART_ID = SRC.P_PARTKEY
WHEN MATCHED THEN
  UPDATE SET
    PART_NAME = SRC.P_NAME,
    PART_MANUFACTURER = SRC.P_MFGR,
    PART_BRAND = SRC.P_BRAND,
    PART_TYPE = SRC.P_TYPE,
    PART_SIZE = SRC.P_SIZE,
    CONTAINER = SRC.P_CONTAINER,
    RETAIL_PRICE = SRC.P_RETAILPRICE,
    LOAD_TIMESTAMP = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN
  INSERT (
    PART_ID,
    PART_NAME,
    PART_MANUFACTURER,
    PART_BRAND,
    PART_TYPE,
    PART_SIZE,
    CONTAINER,
    RETAIL_PRICE,
    LOAD_TIMESTAMP
  )
  VALUES (
    SRC.P_PARTKEY,
    SRC.P_NAME,
    SRC.P_MFGR,
    SRC.P_BRAND,
    SRC.P_TYPE,
    SRC.P_SIZE,
    SRC.P_CONTAINER,
    SRC.P_RETAILPRICE,
    CURRENT_TIMESTAMP()
  );