create or alter table nation_stg (
  nation_id number,
  nation_name varchar,
  region_id number,
  load_timestamp timestamp
);

MERGE INTO WS_DEMO_DB.STG.NATION_STG AS TARGET
USING WS_DEMO_DB.EX.NATION_EXT AS SOURCE
ON TARGET.NATION_ID = SOURCE.N_NATIONKEY
WHEN MATCHED THEN
  UPDATE SET
    NATION_NAME = SOURCE.N_NAME,
    REGION_ID = SOURCE.N_REGIONKEY,
    LOAD_TIMESTAMP = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN
  INSERT (NATION_ID, NATION_NAME, REGION_ID, LOAD_TIMESTAMP)
  VALUES (SOURCE.N_NATIONKEY, SOURCE.N_NAME, SOURCE.N_REGIONKEY, CURRENT_TIMESTAMP());