CREATE OR ALTER TABLE WS_DEMO_DB.STG.CUSTOMER_STG (
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR,
    CUSTOMER_ADDRESS VARCHAR,
    CUSTOMER_NATION NUMBER,
    PHONE_NUMBER VARCHAR,
    ACCOUNT_BALANCE NUMBER,
    MARKET_SEGMENT VARCHAR,
    LOAD_TIMESTAMP TIMESTAMP
);

MERGE INTO WS_DEMO_DB.STG.CUSTOMER_STG AS TGT
USING WS_DEMO_DB.EX.CUSTOMER_EX AS SRC
ON TGT.CUSTOMER_ID = SRC.C_CUSTKEY
WHEN MATCHED THEN
    UPDATE SET
        CUSTOMER_NAME = SRC.C_NAME,
        CUSTOMER_ADDRESS = SRC.C_ADDRESS,
        CUSTOMER_NATION = SRC.C_NATIONKEY,
        PHONE_NUMBER = SRC.C_PHONE,
        ACCOUNT_BALANCE = SRC.C_ACCTBAL,
        MARKET_SEGMENT = SRC.C_MKTSEGMENT,
        LOAD_TIMESTAMP = CURRENT_TIMESTAMP()
WHEN NOT MATCHED THEN
    INSERT (
        CUSTOMER_ID,
        CUSTOMER_NAME,
        CUSTOMER_ADDRESS,
        CUSTOMER_NATION,
        PHONE_NUMBER,
        ACCOUNT_BALANCE,
        MARKET_SEGMENT,
        LOAD_TIMESTAMP
    )
    VALUES (
        SRC.C_CUSTKEY,
        SRC.C_NAME,
        SRC.C_ADDRESS,
        SRC.C_NATIONKEY,
        SRC.C_PHONE,
        SRC.C_ACCTBAL,
        SRC.C_MKTSEGMENT,
        CURRENT_TIMESTAMP()
    );