DEFINE TABLE WS_DEMO_DB.STG.LINEITEM_STG (
    ORDER_ID NUMBER,
    PART_ID NUMBER,
    SUPPLIER_ID NUMBER,
    LINE_NUMBER NUMBER,
    QUANTITY NUMBER,
    EXTENDED_PRICE NUMBER,
    DISCOUNT NUMBER,
    TAX NUMBER,
    RETURN_FLAG VARCHAR,
    LINE_STATUS VARCHAR,
    SHIP_DATE DATE,
    COMMIT_DATE DATE,
    RECEIPT_DATE DATE,
    SHIPPING_INSTRUCTIONS VARCHAR,
    SHIPPING_MODE VARCHAR,
    LOAD_TIMESTAMP TIMESTAMP
);
