DEFINE TABLE WS_DEMO_DB.STG.PART_STG (
    PART_ID NUMBER,
    PART_NAME VARCHAR,
    PART_MANUFACTURER VARCHAR,
    PART_BRAND VARCHAR,
    PART_TYPE VARCHAR,
    PART_SIZE NUMBER,
    CONTAINER VARCHAR,
    RETAIL_PRICE NUMBER,
    LOAD_TIMESTAMP TIMESTAMP
);
