DEFINE TABLE WS_DEMO_DB.STG.CUSTOMER_STG (
    CUSTOMER_ID NUMBER,
    CUSTOMER_NAME VARCHAR,
    CUSTOMER_ADDRESS VARCHAR,
    CUSTOMER_NATION NUMBER,
    PHONE_NUMBER VARCHAR,
    ACCOUNT_BALANCE NUMBER,
    MARKET_SEGMENT VARCHAR,
    LOAD_TIMESTAMP TIMESTAMP
);
