DEFINE TABLE WS_DEMO_DB.STG.ORDERS_STG (
    ORDER_ID NUMBER,
    CUSTOMER_ID NUMBER,
    ORDER_STATUS VARCHAR,
    TOTAL_PRICE NUMBER,
    ORDER_DATE DATE,
    ORDER_PRIORITY VARCHAR,
    CLERK VARCHAR,
    SHIP_PRIORITY NUMBER,
    LOAD_TIMESTAMP TIMESTAMP
);
