CREATE OR REPLACE DYNAMIC TABLE WS_DEMO_DB.MART.DIM_CUSTOMER
TARGET_LAG = '1 hour'
WAREHOUSE = 'DATA_ENGINEER_WH'
AS
SELECT
    CUSTOMER_ID,
    CUSTOMER_NAME,
    CUSTOMER_ADDRESS,
    PHONE_NUMBER,
    MARKET_SEGMENT
FROM WS_DEMO_DB.STG.CUSTOMER_STG;
