CREATE OR REPLACE DYNAMIC TABLE WS_DEMO_DB.MART.FACT_ORDERS
TARGET_LAG = '1 hour'
WAREHOUSE = DATA_ENGINEER_WH
AS
SELECT 
    O.ORDER_ID,
    L.LINE_NUMBER,
    O.CUSTOMER_ID,
    L.PART_ID,
    O.ORDER_DATE,
    O.ORDER_STATUS,
    L.QUANTITY,
    L.EXTENDED_PRICE,
    L.DISCOUNT,
    L.TAX,
    L.LINE_STATUS
FROM WS_DEMO_DB.STG.ORDERS_STG O
JOIN WS_DEMO_DB.STG.LINEITEM_STG L
    ON O.ORDER_ID = L.ORDER_ID;
