CREATE OR REPLACE DYNAMIC TABLE WS_DEMO_DB.MART.DIM_PART
TARGET_LAG = '1 hour'
WAREHOUSE = DATA_ENGINEER_WH
AS
SELECT 
    PART_ID,
    PART_NAME,
    PART_MANUFACTURER,
    PART_BRAND,
    PART_TYPE
    PART_SIZE,
    RETAIL_PRICE
FROM WS_DEMO_DB.STG.PART_STG;
