USE ROLE DATA_ENGINEER;
CREATE SCHEMA WS_DEMO_DB.DEPLOY;

CREATE OR REPLACE GIT REPOSITORY WS_DEMO_GIT_REPO
  API_INTEGRATION = WS_DEMO_GIT_INTEGRATION
  ORIGIN = 'https://github.com/mferle/snowflake-workspaces';

ALTER GIT REPOSITORY WS_DEMO_GIT_REPO FETCH;

LS @WS_DEMO_GIT_REPO/branches/main;

