-- create the DATA_ENGINEER custom role and grant to SYSADMIN
USE ROLE USERADMIN;
CREATE ROLE DATA_ENGINEER;
GRANT ROLE DATA_ENGINEER TO ROLE SYSADMIN;

-- create the WS_DEMO_DB database and grant ownership to the DATA_ENGINEER role
USE ROLE SYSADMIN;
CREATE DATABASE WS_DEMO_DB;
GRANT OWNERSHIP ON DATABASE WS_DEMO_DB TO ROLE DATA_ENGINEER;

-- create the DATA_ENGINEER_WH warehouse and grant usage to the DATA_ENGINEER role
CREATE WAREHOUSE DATA_ENGINEER_WH WITH WAREHOUSE_SIZE = 'XSMALL' AUTO_SUSPEND = 60 AUTO_RESUME = TRUE;
GRANT USAGE ON WAREHOUSE DATA_ENGINEER_WH TO ROLE DATA_ENGINEER;

-- use the DATA_ENGINEER role to create schemas
USE ROLE DATA_ENGINEER;
CREATE SCHEMA WS_DEMO_DB.EX;
CREATE SCHEMA WS_DEMO_DB.STG;
CREATE SCHEMA WS_DEMO_DB.MART;
